runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:p3Rrd3u3W6SaJyZzTxN40Ve9+yd6GD+iWt8cI7Xfi+s=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  DB_SOCKET: "/cloudsql/glocals-197409:asia-east1:glocalsinstance"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "glocals-197409:asia-east1:glocalsinstance"